name: Semgrep SAST

on:
  push:
    branches: [ "**" ]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep SAST
        uses: semgrep/semgrep-action@v1
        with:
          config: auto
